![Credit card being held in hand](credit_card.jpg)

Commercial banks receive _a lot_ of applications for credit cards. Many of them get rejected for many reasons, like high loan balances, low income levels, or too many inquiries on an individual's credit report, for example. Manually analyzing these applications is mundane, error-prone, and time-consuming (and time is money!). Luckily, this task can be automated with the power of machine learning and pretty much every commercial bank does so nowadays. In this workbook, you will build an automatic credit card approval predictor using machine learning techniques, just like real banks do.

### The Data

The data is a small subset of the Credit Card Approval dataset from the UCI Machine Learning Repository showing the credit card applications a bank receives. This dataset has been loaded as a `pandas` DataFrame called `cc_apps`. The last column in the dataset is the target value.

In [13]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

# Load the dataset
cc_apps = pd.read_csv("cc_approvals.data", header=None) 
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11   12 13
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  g    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  g  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  g  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  g    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  s    0  +

In [14]:
cc_apps = cc_apps.replace('?', np.nan)
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11   12 13
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  g    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  g  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  g  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  g    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  s    0  +

In [15]:
cc_apps.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13     0
dtype: int64

In [16]:
cc_apps.fillna(cc_apps.mean(numeric_only=True), inplace=True)

for col in cc_apps.columns:
    if cc_apps[col].dtype == 'object':
        cc_apps[col].fillna(cc_apps[col].mode()[0], inplace=True)

cc_apps.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
dtype: int64

In [17]:
cc_apps = pd.get_dummies(cc_apps)
cc_apps.head()

       2     7  10   12  0_a  0_b  ...  9_t  11_g  11_p  11_s  13_+  13_-
0  0.000  1.25   1    0    0    1  ...    1     1     0     0     1     0
1  4.460  3.04   6  560    1    0  ...    1     1     0     0     1     0
2  0.500  1.50   0  824    1    0  ...    0     1     0     0     1     0
3  1.540  3.75   5    3    0    1  ...    1     1     0     0     1     0
4  5.625  1.71   0    0    0    1  ...    0     0     0     1     1     0

[5 rows x 393 columns]

In [18]:
X = cc_apps.iloc[:, :-1]
y = cc_apps.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)

(552, 392)
(138, 392)

In [19]:
# Fix: Ensure all column names are strings
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Done scaling")

Done scaling

In [20]:
param_grid = {
    'tol': [0.01, 0.001, 0.0001],
    'max_iter': [100, 150, 200],
    'C': [0.01, 0.1, 1, 10]
}

grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)

Best parameters: {'C': 10, 'max_iter': 100, 'tol': 0.01}

In [21]:
best_score = grid_search.best_estimator_.score(X_test, y_test)
print("Best accuracy score:", best_score)

Best accuracy score: 0.9855072463768116